#!/usr/bin/env bash
#
# init_pki - Initialize example TLS CA/root certificates for Vaultron
#

openssl req \
    -x509 \
    -batch \
    -nodes \
    -newkey rsa:2048 \
    -keyout vaultron.key \
    -out vaultron.crt \
    -config vaultron_root.cfg \
    -days 365
