#!/bin/sh
#
# blazing_sword
#
# Automatically starts a Vault cluster for use in development or other
# evaluation style use cases:
#
# - Initialize Vault
# - Save key material to temporary file
# - Unseal Vault with key material from temporary file
# - Enable a range of auth and secret backends with default mounts
#
# ‼️ PLEASE DO NOT USE THIS IN PRODUCTION ‼️
#
# Pick one, fix one!
# shellcheck disable=SC1117,SC2154,SC2059,SC2039,SC1091

. ./skydome

# Check for the existence of a temporary key material file
check_vault_file() {
  for file in ./vault/vault_*.tmp; do
    if [ -e "$file" ]; then
        msg info "Existing Vault file detected; pass filename as first argument and it will be used for unsealing."
        exit 0
    fi
  done
}

# Emit a little usage note
usage() {
  msg alert "Usage: vault_kitchen_sink [vault_dat.tmp]"
  exit 1
}

# Authenticate with initial root token
auth_root() {
  msg info "Authenticating with Vault root token ..."
  get_initial_root_token "${vault_dat}"
  vault auth "${init_root_token}"  > /dev/null 2>&1
}

# Show enabled auth methods and secrets engines
enabled() {
  msg info "Enabled Auth Methods and Secrets Engines"
  check_cli_cap
  if [ "$vault_cli_cap" -eq "1" ]; then
    v_auth_list_cmd="vault auth list"
  else
    v_auth_list_cmd="vault auth -methods"
  fi
  if [ "$vault_cli_cap" -eq "1" ]; then
    v_secret_list_cmd="vault secrets list"
  else
    v_secret_list_cmd="vault mounts"
  fi
  $v_auth_list_cmd
  $v_secret_list_cmd
}

# Enable audit log
enable_audit_logging() {
  msg complete "Enabled file based audit log at ./vault/logs/audit.log!"
  auth_root
  vault audit-enable file file_path=/vault/logs/audit.log  > /dev/null 2>&1
}

# Enable authentication backends
enable_auth_backends() {
  check_cli_cap
  if [ "$vault_cli_cap" -eq "1" ]; then
    v_auth_cmd="vault auth enable"
  else
    v_auth_cmd="vault auth-enable"
  fi
  msg info "Enabling Vault authentication backends ..."
  auth_root

  $v_auth_cmd -path=vaultron_approle approle > /dev/null 2>&1
  msg complete "Enabled AppRole authentication backend at vaultron_approle!"

  # TODO: This needs to be conditionally added based on installed Vault
  # version as aws auth does not exist in older Vault versions
  #
  # vault auth-enable aws > /dev/null 2>&1
  # msg complete "Enabled AWS authentication backend!"
  #

  $v_auth_cmd -path=vaultron_ldap ldap > /dev/null 2>&1
  msg complete "Enabled LDAP authentication backend at vaultron_ldap!"

  $v_auth_cmd -path=vaultron_userpass userpass > /dev/null 2>&1
  msg complete "Enabled Username & Password authentication backend at vaultron_userpass!"
}

# Get a subset of unseal keys
get_unseal_keys() {
  msg info "Get unseal keys ..."
  k1=$(grep 'Unseal Key 1' "${vault_dat}" | awk '{print $NF}')
  k2=$(grep 'Unseal Key 2' "${vault_dat}" | awk '{print $NF}')
  k3=$(grep 'Unseal Key 3' "${vault_dat}" | awk '{print $NF}')
}

# Get the initial root token
get_initial_root_token() {
  init_root_token=$(grep 'Initial Root Token' "${1}" | awk '{print $NF}')
}

# Initialize Vault and save temporary unseal keys and root token
initialize_vault() {
  check_cli_cap
  if [ "$vault_cli_cap" -eq "1" ]; then
    v_init_cmd="vault operator init"
  else
    v_init_cmd="vault init"
  fi
  msg info "Initializing Vault ..."
  vault_dat="./vault/vault_DEV_ONLY-$(date +%s).tmp"
  if ! $v_init_cmd | perl -pe 's/\x1b\[[0-9;]*m//g' > "${vault_dat}"; then
    errors=$((errors + $?))
    msg alert "Failed to initialize Vault!"
    exit $errors
  else
    msg complete "Vault initialized!"
  fi
}

# Enable database secrets engine
mount_database_backend() {
  check_cli_cap
  if [ "$vault_cli_cap" -eq "1" ]; then
    v_enable_cmd="vault secrets enable"
  else
    v_enable_cmd="vault mount"
  fi
  msg info "Enabling database secrets engine ..."
  get_initial_root_token "${vault_dat}"
  if ! $v_enable_cmd -path=vaultron_database database> /dev/null 2>&1; then
    msg alert "Problem enabling database secrets engine!"
  else
    msg complete "Enabled database secrets engine!"
  fi
}

# Enable a handy mix of secrets engines
mount_secret_backends() {
  check_cli_cap
  if [ "$vault_cli_cap" -eq "1" ]; then
    v_enable_cmd="vault secrets enable"
  else
    v_enable_cmd="vault mount"
  fi
  msg info "Mounting Vault secret backends ..."
  get_initial_root_token "${vault_dat}"

  if ! $v_enable_cmd -path=vaultron_kv kv > /dev/null 2>&1; then
    errors=$((errors + $?))
    msg alert "Problem enabling KV secrets engine at vaultron_kv!"
    exit $errors
  else
  msg complete "Enabled KV secrets engine at vaultron_kv!"
  fi

  if ! $v_enable_cmd -path=vaultron_aws aws > /dev/null 2>&1; then
    errors=$((errors + $?))
    msg alert "Problem enabling AWS secrets engine at vaultron_aws!"
    exit $errors
  else
  msg complete "Enabled AWS secrets engine at vaultron_aws!"
  fi

  if ! $v_enable_cmd -path=vaultron_consul consul > /dev/null 2>&1; then
    errors=$((errors + $?))
    msg alert "Problem enabling Consul secrets engine at vaultron_consul!"
    exit $errors
  else
  msg complete "Enabled Consul secrets engine at vaultron_consul!"
  fi

  if ! $v_enable_cmd -path=vaultron_root_pki pki > /dev/null 2>&1; then
    errors=$((errors + $?))
    msg alert "Problem enabling PKI secrets engine at vaultron_root_pki!"
    exit $errors
  else
  msg complete "Enabled PKI secrets engine at vaultron_root_pki!"
  fi

  if ! $v_enable_cmd -path=vaultron_int_pki pki > /dev/null 2>&1; then
    errors=$((errors + $?))
    msg alert "Problem enabling PKI secrets engine at vaultron_int_pki!"
    exit $errors
  else
  msg complete "Enabled PKI secrets engine at vaultron_int_pki!"
  fi

  if ! $v_enable_cmd -path=vaultron_transit transit > /dev/null 2>&1; then
    errors=$((errors + $?))
    msg alert "Problem enabling Transit secrets engine at vaultron_transit!"
    exit $errors
  else
  msg complete "Enabled Transit secrets engine at vaultron_transit!"
  fi

  if ! $v_enable_cmd -path=vaultron_ssh_host_signer ssh > /dev/null 2>&1; then
    errors=$((errors + $?))
    msg alert "Problem enabling SSH secrets engine at vaultron_ssh_host_signer!"
    exit $errors
  else
  msg complete "Enabled SSH secrets engine at vaultron_ssh_host_signer!"
  fi

  if ! $v_enable_cmd -path=vaultron_ssh_client_signer ssh > /dev/null 2>&1; then
    errors=$((errors + $?))
    msg alert "Problem enabling SSH secrets engine at vaultron_ssh_client_signer!"
    exit $errors
  else
  msg complete "Enabled SSH secrets engine at vaultron_ssh_client_signer!"
  fi
}

# Get Vault status
status() {
  msg info "Vault status ..."
  printf "$(vault status)\n"
}

# Unseal Vault
unseal_vault() {
  check_cli_cap
  if [ "$vault_cli_cap" -eq "1" ]; then
    v_unseal_cmd="vault operator unseal"
  else
    v_unseal_cmd="vault unseal"
  fi
  msg info "Unsealing Vault ..."
  get_unseal_keys
  for i in {0..2}; do
    if ! VAULT_ADDR="http://localhost:820${i}" \
      $v_unseal_cmd $k1 > /dev/null 2>&1; then
      msg alert "Failed to unseal Vault 1"
      errors=$((errors + $?))
      exit $errors
    fi
    if ! VAULT_ADDR="http://localhost:820${i}" \
      $v_unseal_cmd $k2 > /dev/null 2>&1; then
      msg alert "Failed to unseal vault 2"
      errors=$((errors + $?))
      exit $errors
    fi
    if ! VAULT_ADDR="http://localhost:820${i}" \
      $v_unseal_cmd $k3 > /dev/null 2>&1; then
      msg alert "Failed to unseal Vault 3"
      errors=$((errors + $?))
      exit $errors
    fi
  done
  msg complete "Vault unsealed!"
}

# DO IT.
if [ $# -gt 1 ]
  then
    usage
fi

if (set -u; : "${1}") 2> /dev/null; then
  msg info "Filename argument specified; Use file: ${1}"
  vault_dat="${1}"
  k1=$(grep 'Unseal Key 1' "${vault_dat}" | awk '{print $NF}')
  k2=$(grep 'Unseal Key 2' "${vault_dat}" | awk '{print $NF}')
  k3=$(grep 'Unseal Key 3' "${vault_dat}" | awk '{print $NF}')
  msg info "Unsealing by default since filename used ..."
  for i in {0..2}; do
    VAULT_ADDR="http://localhost:820${i}" \
    vault unseal "${k1}" > /dev/null 2>&1 && \
    VAULT_ADDR="http://localhost:820${i}" \
    vault unseal "${k2}" > /dev/null 2>&1 && \
    VAULT_ADDR="http://localhost:820${i}" \
    vault unseal "${k3}" > /dev/null 2>&1;
  done
  auth_root
  status
  exit 0
else
  msg greeting "Form Blazing Sword! ..."
fi

unset VAULT_TOKEN
initialize_vault
unseal_vault
auth_root
enable_auth_backends
enable_audit_logging
mount_secret_backends
mount_database_backend
status
enabled
