#!/bin/sh
#
# ion_darts
#
# Set the Consul and Vault environment variables
# to correct values for Vaultron
#
# shellcheck disable=SC1091

. ./skydome

CONSUL_CACERT="$(pwd)/red_lion/tls/ca-bundle.pem"
CONSUL_HTTP_ADDR="127.0.0.1:8500"
CONSUL_HTTP_SSL=true
CONSUL_HTTP_TOKEN="vaultron-forms-and-eats-all-the-tacos-in-town"
VAULT_ADDR="https://127.0.0.1:8200"
VAULT_CACERT="$(pwd)/black_lion/tls/ca-bundle.pem"
export \
CONSUL_CACERT \
CONSUL_HTTP_ADDR \
CONSUL_HTTP_SSL \
CONSUL_HTTP_TOKEN \
VAULT_ADDR \
VAULT_CACERT
msg success "Exported Vaultron environment variables!"
