#!/bin/sh
#
# ion_darts
#
# Set the Consul and Vault environment variables
# to correct values for Vaultron
#
# shellcheck disable=SC1091

. ./skydome

msg greeting "Exporting Vaultron environment variables ..."
export CONSUL_HTTP_ADDR="127.0.0.1:8500"
export VAULT_ADDR="http://127.0.0.1:8200"
export CONSUL_HTTP_TOKEN="vaultron-forms-and-eats-all-the-tacos-in-town"
msg success "Exported Vaultron environment variables!"
