#!/bin/sh
# =======================================================================
# This script contains common functions and is sourced by the
# the other Vaultron scripts; there's nothing useful in here to run directly.
#
# shellcheck disable=SC2059
#                       ^
# NB: we must roll with this sole shellcheck exception because the ANSI
#     escape sequences as expanded by string formatting are ineffective
#     leading the printing of literal characters instead, for example:
#         \033[0;36m[=]%sForm Vaultron! ...%s\n\033[0mn
#     so we take the ding in the name of ANSI color greatness
#     (void where prohibited)
# =======================================================================

export VAULTRON_TMP="$PWD/tmp"

# Colors
TXTBLU="$(tput setaf 4)"
TXTCYA="$(tput setaf 6)"
TXTGRN="$(tput setaf 2)"
TXTMGT="$(tput setaf 5)"
TXTRED="$(tput setaf 1)"
TXTYLW="$(tput setaf 3)"
TXTWHT="$(tput setaf 7)"
TXTRST="$(tput sgr0)"

msg() {
    MSGSRC="[vaultron]"
    MSGTYPE="$1"
    MSGTXT="$2"
    case "${MSGTYPE}" in
        greeting)
            printf "%s%s [=] %s %s\\n" "$TXTBLU" "$MSGSRC" "$MSGTXT" "$TXTRST"
            ;;
        info)
            printf "%s%s [i] %s %s\\n" "$TXTWHT" "$MSGSRC" "$MSGTXT" "$TXTRST"
            ;;
        success)
            printf "%s%s [+] %s %s\\n" "$TXTGRN" "$MSGSRC" "$MSGTXT" "$TXTRST"
            ;;
        complete)
            printf "%s%s [^] %s %s\\n" "$TXTGRN" "$MSGSRC" "$MSGTXT" "$TXTRST"
            ;;
        boom)
            printf "%s%s [*] %s %s\\n" "$TXTMGT" "$MSGSRC" "$MSGTXT" "$TXTRST"
            ;;
        notice)
            printf "%s%s [-] %s %s\\n" "$TXTYLW" "$MSGSRC" "$MSGTXT" "$TXTRST"
            ;;
        alert)
            printf "%s%s [!] %s %s\\n" "$TXTRED" "$MSGSRC" "$MSGTXT" "$TXTRST"
            ;;
        *)
            printf "%s%s [@] %s %s\\n" "$TXTCYA" "$MSGSRC" "$MSGTXT" "$TXTRST"
            ;;
    esac
}

# -----------------------------------------------------------------------
# Check CLI capabilities for renaming from <= v0.9.1 and v0.9.1+
# -----------------------------------------------------------------------

check_cli_cap() {
  VAULT_VERSION="$(vault version | awk '{print $2}' | cut -d 'v' -f2)"
  VAULT_MIN_VERSION="$(vault version | awk '{print $2}' | cut -d 'v' -f2 | cut -d '.' -f2)"
  if [ "$VAULT_VERSION" = "0.9.1" ] || [ "$VAULT_MIN_VERSION" -lt "9" ]; then
    export VAULT_CLI_CAP="0"
  else
    export VAULT_CLI_CAP="1"
  fi
}

# Begin Terraform specific bits
tfmsg() {
    tfmsg_out="$(echo "$1" | awk '{
           # strip control characters for printing and matching
           gsub(/\033\[[0-9]+m/,"")
        }
        /^(Apply complete|Destroy complete|Plan:)/ {
            print "info"
            print "Terraform", tolower($0)
            exit
        }
        /^Terraform.*initialized!/ {
            print "info"
            print
            exit
        }
        /^([0-9]+ error\(s\) occurred:|Failed to load backend)/ {
            print "alert"
            sub(/:.*/,"")
            print "Terraform", tolower($0)
            exit
        }')"

    if [ -n "$tfmsg_out" ]; then
        msg "$(echo "$tfmsg_out" | head -1)" \
                "$(echo "$tfmsg_out" | tail -1)"
    fi
}

tflogdir() {
    if ! [ -d ./log ]; then
        mkdir ./log
    fi
}

init() {
    tfout="$(terraform init 2>&1)"
    ret=$?
    init_out="./log/tf-$(date -u "+%Y-%m-%dT%H:%M:%SZ")-init.log"
    echo "$tfout" > "$init_out"
    tfmsg "$tfout"
    return $ret
}

apply() {
    tfout="$(terraform apply -auto-approve "$1" 2>&1)"
    ret=$?
    apply_out="./log/tf-$(date -u "+%Y-%m-%dT%H:%M:%SZ")-apply.log"
    echo "$tfout" > "$apply_out"
    tfmsg "$tfout"
    return $ret
}

plan() {
    tfout="$(terraform plan -out="$1" 2>&1)"
    ret=$?
    plan_out="./log/tf-$(date -u "+%Y-%m-%dT%H:%M:%SZ")-plan.log"
    echo "$tfout" > "$plan_out"
    tfmsg "$tfout"
    return $ret
}

destroy() {
    tfout="$(terraform destroy -force -state=./tfstate/terraform.tfstate 2>&1)"
    echo "$tfout" > ./log/tf-"$(date -u "+%Y-%m-%dT%H:%M:%SZ")"-destroy.log
    tfmsg "$tfout"
    return $ret
}
