#!/bin/sh

echo "🤖  Unform Vaultron ..."

terraform destroy -force -state=./tfstate/terraform.tfstate \
    > ./log/tf-destroy-$(date -u "+%Y-%m-%dT%H:%M:%SZ").log 2>&1
errors=$?
if [ 0 -ne $errors ]; then
    echo "🚫   Terraform destroy failed, infrastructure may still exist."
fi

###
### Remove Consul client data
###
rm -rf ./consul/consul_oss_client_1
errors=$(( $errors + $?))
rm -rf ./consul/consul_oss_client_2
errors=$(( $errors + $?))
rm -rf ./consul/consul_oss_client_3
errors=$(( $errors + $?))

###
### Remove Consul server data
###
rm -rf ./consul/consul_oss_server_1
errors=$(( $errors + $?))
rm -rf ./consul/consul_oss_server_2
errors=$(( $errors + $?))
rm -rf ./consul/consul_oss_server_3
errors=$(( $errors + $?))

###
### Remove Vault server data
###
rm -rf ./vault/vault_oss_server_1
errors=$(( $errors + $?))
rm -rf ./vault/vault_oss_server_2
errors=$(( $errors + $?))
rm -rf ./vault/vault_oss_server_3
errors=$(( $errors + $?))
rm -rf ./vault/vault_*.tmp
errors=$(( $errors + $?))

###
### Remove Terraform state
###
rm -rf ./tfstate/terraform.tfstate*
errors=$(( $errors + $?))

if [ $errors -gt 0 ]; then
    echo "💥  Vaultron unformed (with $errors errors)!"
else
    echo "💥  Vaultron unformed!"
fi

exit $errors

