#!/usr/bin/env bash
#
# gen_kv_secrets
#
# Sequentially create N KV secrets in Vault at the path "vaultron-kv/test"
#
# shellcheck disable=SC2086,SC2089,SC2090,SC1090,SC1091,SC2059

HERE="$(pwd)"
SKYDOME="$(while [ "$HERE" != "/" ] ; do HERE=$(dirname "$HERE"); find "$HERE" -maxdepth 1 -name skydome; done)"
if [ -z "$SKYDOME" ]; then
  SKYDOME=./skydome
fi
. $SKYDOME

PROGRAM="$(basename "$0")"

usage() {
  printf "${TXTYLW} ${PROGRAM} - sequentially generate KV secrets${TXTRST}\\n"
  printf "${TXTYLW} ${TXTRST}\\n"
  printf "${TXTYLW} ${PROGRAM} [options]${TXTRST}\\n"
  printf "${TXTYLW} ${TXTRST}\\n"
  printf "${TXTYLW} options:${TXTRST}\\n"
  printf "${TXTYLW} -h, --help           show brief help${TXTRST}\\n"
  printf "${TXTYLW} -c, --count=100      specify generated secrets total count${TXTRST}\\n"
  printf "${TXTYLW} -p, --path=secret    specify target KV Secrets Engine path${TXTRST}\\n"
  exit 1
}

check_vault() {
  if command nc; then
    PORT_CHECK="nc -z locahost 8200";
  elif command timeout; then
    PORT_CHECK="timeout 1 bash -c '</dev/tcp/localhost/8200'"
  elif command gtimeout; then
    PORT_CHECK="gtimeout 1 bash -c '</dev/tcp/localhost/8200'"
  fi
}

gen_secrets() {
  while [ "$1" != "" ]; do
      PARAM=$(echo $1 | awk -F= '{print $1}')
      VALUE=$(echo $1 | awk -F= '{print $2}')
      case $PARAM in
          -h | --help)
              usage
              exit
              ;;
          --count)
              KV_COUNT=$VALUE
              ;;
          -c)
              KV_COUNT=$VALUE
              ;;
          --path)
              KV_PATH=$VALUE
              ;;
          -p)
              KV_PATH=$VALUE
              ;;
          *)
              echo "ERROR: unknown parameter \"$PARAM\""
              usage
              exit 1
              ;;
      esac
      shift
  done

  while [[ $i -le $KV_COUNT ]]; do
    SEC_ITEM="$KV_PATH/test/$(openssl rand -hex 8) id=$(uuidgen)"
    if ! vault write $SEC_ITEM > /dev/null 2>&1; then
      msg error "Cannot write secret $SEC_ITEM"
      export KV_COUNT=1
    else
      msg secret "Created KV secret at path: ${SEC_ITEM}"
      ((i = i + 1))
    fi
  done
}

[ $# -eq 0 ] && usage

if $PORT_CHECK; then
  gen_secrets "$@"
else
  echo "Not sure if Vault is reachable at localhost! Giving up!"
  exit 1
fi
