#!/usr/bin/env bash
#
# gen_generic_secrets
#
# Sequentially create N generic secrets in Vault
#
# shellcheck disable=SC2086
# shellcheck disable=SC2089
# shellcheck disable=SC2090
# shellcheck disable=SC1091
#

. ./skydome

program="$(basename "$0")"

if [ $# -eq 0 ]
  then
    echo "Usage: ${program} <number_of_secrets>"
    exit 1
fi

check_vault() {
  if command nc; then
    PORT_CHECK="nc -z locahost 8200";
  elif command timeout; then
    PORT_CHECK="timeout 1 bash -c '</dev/tcp/localhost/8200'"
  elif command gtimeout; then
    PORT_CHECK="gtimeout 1 bash -c '</dev/tcp/localhost/8200'"
  fi
}

gen_secrets() {
  while [[ $i -le $1 ]]; do
    sec_item="secret/test/$(openssl rand -hex 8) id=$(uuidgen)"
    vault write $sec_item > /dev/null 2>&1
    msg complete "🔑  Secret: ${sec_item}"
    ((i = i + 1))
  done
}

if $PORT_CHECK; then
  gen_secrets "$@"
else
  echo "Not sure if Vault is reachable at localhost! Giving up!"
  exit 1
fi
