#!/usr/bin/env bash
#
# gen_generic_secrets
#
# Sequentially create N generic secrets in Vault
#
# shellcheck disable=SC2086
# shellcheck disable=SC1091
#

. ./skydome

program="$(basename "$0")"

if [ $# -eq 0 ]
  then
    echo "Usage: ${program} <number_of_secrets>"
    exit 1
fi

while [[ $i -le $1 ]]; do
  sec_item="secret/bar$i id=$(uuidgen)"
  vault write $sec_item > /dev/null 2>&1
  _logmsg complete "Item: ${sec_item}"
  ((i = i + 1))
done
