#!/usr/bin/env bash
#
# gen_consul_kv
#
# Create various oddball entries in the Consul K/V for testing, etc.
#
# shellcheck disable=SC1090,SC1091

HERE="$(pwd)"
SKYDOME="$(while [ "$HERE" != "/" ] ; do HERE=$(dirname "$HERE"); find "$HERE" -maxdepth 1 -name skydome; done)"
if [ -z "$SKYDOME" ]; then
  SKYDOME=./skydome
fi
. $SKYDOME

create_kv() {
    for i in {1..100}; do
        HW_ADDR="$(openssl rand -hex 6)"
        curl \
        --request PUT \
        --data "hwaddr=${HW_ADDR}" \
        "${CONSUL_HTTP_ADDR}/v1/kv/${1}/vaultron-test-key-${i}";
    done
}

check_vault

for n in foo bar baz qux; do
    msg info "PUT keys in ${CONSUL_HTTP_ADDR}/v1/kv/${n}/"
    create_kv "${n}";
done
