#!/usr/bin/env bash
#
# vault_snap_test
#
# An example use case test for Vault secret
# addition/deletion/restoration
#
# shellcheck disable=SC1091
#

. ./skydome

SECRET="secret/bar"
SECRET_VALUE="baz"
SNAPSHOT="newBack.snap"

#_logmsg() {
#    if [ "$1" == "alert" ]; then
#        echo >&2  "[e] $2";
#    else
#        echo "[+] $2";
#    fi
#}

_delete() {
  if vault delete "${SECRET}" > /dev/null 2>&1 ; then
      retval=0
  else
    retval=1
    return "$retval"
  fi
}

_read() {
  if vault read "${SECRET}" > /dev/null 2>&1 ; then
      retval=0
  else
      retval=1
  fi
  return "$retval"
}

_snapshot_restore() {
  if consul snapshot restore "$1" > /dev/null 2>&1; then
    retval=0
  else
    retval=1
  fi
  return "$retval"
}

_snapshot_save() {
  if consul snapshot save "$1" > /dev/null 2>&1; then
    retval=0
  else
    retval=1
  fi
  return "$retval"
}

_write() {
  if vault write "${SECRET}" value="${SECRET_VALUE}" > /dev/null 2>&1; then
    retval=0
  else
    retval=1
  fi
  return "$retval"
}

if _write; then
  _logmsg info "Write 1 OK";
else
  _logmsg alert "Write 1 Failed";

fi

if _read; then
  _logmsg info "Read 1 OK";
else
  _logmsg alert "Read 1 Failed";

fi

if _snapshot_save "$SNAPSHOT"; then
  _logmsg info "Snapshot save 1 OK";
else
  _logmsg alert "Snapshot save 1 Failed";

fi

if _read; then
  _logmsg info "Read 2 OK";
else
  _logmsg alert "Read 2 Failed";

fi

if _delete; then
  _logmsg info "Delete 1 OK";
else
  _logmsg alert "Delete 1 Failed";

fi

if _read; then
  _logmsg info "Read 3 (immediately after delete 1) OK";
else
  _logmsg alert "Read 3 (immediately after delete 1) Failed";

fi

if _snapshot_restore "${SNAPSHOT}"; then
  _logmsg info "Snapshot restore 1 OK";
else
  _logmsg alert "Snapshot restore 1 Failed";

fi

if _read; then
  _logmsg info "Read 4 OK";
else
  _logmsg alert "Read 4 Failed";

fi

if _delete; then
  _logmsg info "Delete 2 OK";
else
  _logmsg alert "Delete 2 Failed";

fi

if _read; then
  _logmsg info "Read 5 (immediately after delete 2) OK";
else
  _logmsg alert "Read 5 (immediately after delete 2) Failed";

fi

if _snapshot_restore "${SNAPSHOT}"; then
  _logmsg info "Snapshot restore 2 OK";
else
  _logmsg alert "Snapshot restore 2 Failed";

fi

if _read; then
  _logmsg info "Read 6 OK";
else
  _logmsg alert "Read 6 Failed";

fi
